modify

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -38,51 +38,55 @@ jobs:
               --parameter-overrides DBPassword=$DB_PASSWORD EnvironmentName=$ENVIRONMENT_NAME \
               --capabilities CAPABILITY_NAMED_IAM
 
-      - run:
-          name: Write env vars to bash.env
-          command: |
-            set -eo pipefail
-
-            STACK_NAME="<< pipeline.parameters.NameBase >>-application"
-
-            EC2_PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)
-            DB_USER=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)
-            DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)
-            DB_HOST=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)
-            S3_BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)
-            ALB_HOST=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)
-
-            echo "export AWS_EC2_PUBLIC=$EC2_PUBLIC_IP" > bash.env
-            echo "export DB_USER=$DB_USER" >> bash.env
-            echo "export DB_PASSWORD=$DB_PASSWORD" >> bash.env
-            echo "export DB_HOST=$DB_HOST" >> bash.env
-            echo "export S3_BUCKET=$S3_BUCKET" >> bash.env
-            echo "export ALB_HOST=$ALB_HOST" >> bash.env
-
-            echo "--- bash.env 作成内容 ---"
-            cat bash.env
-
       # - run:
       #     name: Write env vars to bash.env
       #     command: |
-      #       echo "export AWS_EC2_PUBLIC=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)" >> bash.env
-      #       echo "export DB_USER=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)" >> bash.env
-      #       echo "export DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)" >> bash.env
-      #       echo "export DB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)" >> bash.env
-      #       echo "export S3_BUCKET=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)" >> bash.env
-      #       echo "export ALB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)" >> bash.env
+      #       set -eo pipefail
+
+      #       STACK_NAME="<< pipeline.parameters.NameBase >>-application"
+
+      #       EC2_PUBLIC_IP=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)
+      #       DB_USER=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)
+      #       DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)
+      #       DB_HOST=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)
+      #       S3_BUCKET=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)
+      #       ALB_HOST=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)
+
+      #       echo "export AWS_EC2_PUBLIC=$EC2_PUBLIC_IP" > bash.env
+      #       echo "export DB_USER=$DB_USER" >> bash.env
+      #       echo "export DB_PASSWORD=$DB_PASSWORD" >> bash.env
+      #       echo "export DB_HOST=$DB_HOST" >> bash.env
+      #       echo "export S3_BUCKET=$S3_BUCKET" >> bash.env
+      #       echo "export ALB_HOST=$ALB_HOST" >> bash.env
+
+      #       echo "--- bash.env 作成内容 ---"
+      #       cat bash.env
+
+      - run:
+          name: Write env vars to bash.env
+          command: |
+            echo "export AWS_EC2_PUBLIC=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)" >> $BASH_ENV
+            echo "export DB_USER=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)" >> $BASH_ENV
+            echo "export DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)" >> $BASH_ENV
+            echo "export DB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)" >> $BASH_ENV
+            echo "export S3_BUCKET=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)" >> $BASH_ENV
+            echo "export ALB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)" >> $BASH_ENV
+
+      - run:
+          command: 
+            cp $BASH_ENV bash.env
 
       - persist_to_workspace:  # `bash.env` をワークスペースに保存
           root: .
           paths:
             - bash.env
-      - run:
-          name: Debug print EC2 IP directly
-          command: |
-            aws cloudformation describe-stacks \
-              --stack-name << pipeline.parameters.NameBase >>-application \
-              --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' \
-              --output text 
+      # - run:
+      #     name: Debug print EC2 IP directly
+      #     command: |
+      #       aws cloudformation describe-stacks \
+      #         --stack-name << pipeline.parameters.NameBase >>-application \
+      #         --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' \
+      #         --output text 
   ansible:
     executor: ansible-playbook/default
     steps:
@@ -91,18 +95,21 @@ jobs:
          at: .
 
       - run:
-          name: Load environment variables from bash.env
-          command: |
-            if [ -f bash.env ]; then
-              set -o allexport
-              source bash.env
-              set +o allexport
-              echo "bash.env loaded"
-              echo "AWS_EC2_PUBLIC=$AWS_EC2_PUBLIC"
-            else
-              echo "bash.env not found!"
-              exit 1
-            fi
+          command: 
+            cat bash.env >> $BASH_ENV
+
+      # - run:
+      #     name: Load environment variables from bash.env
+      #     command: |
+      #       if [ -f bash.env ]; then
+      #         set -o allexport
+      #         source bash.env
+      #         set +o allexport
+      #         echo "bash.env loaded"
+      #       else
+      #         echo "bash.env not found!"
+      #         exit 1
+      #       fi
 
       - run:
           name: Check ENV var
