modify

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -88,15 +88,30 @@ jobs:
     steps:
       - checkout
       - attach_workspace:
-          at: .
+         at: .
+
       - run:
-          name: Load environment variables
+          name: Load environment variables from bash.env
           command: |
             if [ -f bash.env ]; then
               set -o allexport
               source bash.env
               set +o allexport
+              echo "bash.env loaded"
+              echo "AWS_EC2_PUBLIC=$AWS_EC2_PUBLIC"
+            else
+              echo "bash.env not found!"
+              exit 1
             fi
+
+      - run:
+          name: Check ENV var
+          command: |
+            echo "AWS_EC2_PUBLIC=$AWS_EC2_PUBLIC"
+            echo "DB_USER=$DB_USER"
+            echo "DB_PASSWORD=$DB_PASSWORD"
+            echo "DB_HOST=$DB_HOST"
+            echo "S3_BUCKET=$S3_BUCKET"
 
       - run:
           name: Install boto3 and botocore
@@ -151,14 +166,7 @@ jobs:
       #       echo "S3_BUCKET: $S3_BUCKET"
       #       cat bash.env
       
-      - run:
-          name: Check ENV var
-          command: |
-            echo "AWS_EC2_PUBLIC=$AWS_EC2_PUBLIC"
-            echo "DB_USER=$DB_USER"
-            echo "DB_PASSWORD=$DB_PASSWORD"
-            echo "DB_HOST=$DB_HOST"
-            echo "S3_BUCKET=$S3_BUCKET"
+
       
       - run:
           name: Run Ansible Playbook
