modify

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,76 +41,18 @@ jobs:
       - run:
           name: Set Environment Variables for Ansible
           command: |
-            echo "export AWS_EC2_PUBLIC=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)" >> $BASH_ENV
-            echo "export DB_USER=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)" >> $BASH_ENV
-            echo "export DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)" >> $BASH_ENV
-            echo "export DB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)" >> $BASH_ENV
-            echo "export S3_BUCKET=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)" >> $BASH_ENV
-            echo "export ALB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)" >> $BASH_ENV
-            source "$BASH_ENV"
-            echo "AWS_EC2_PUBLIC: $AWS_EC2_PUBLIC"
-            echo "DB_USER: $DB_USER"
-            echo "DB_PASSWORD: $DB_PASSWORD"
-            echo "DB_HOST: $DB_HOST"
-            echo "S3_BUCKET: $S3_BUCKET"
-            echo "ALB_HOST: $ALB_HOST"
-          
-      - run:
-          name: Install boto3 and botocore
-          command: |
-            pip install boto3 botocore
-      - run:
-          name: Verify boto3 installation
-          command: python -m pip show boto3
-      - run:
-          name: Verify botocore installation
-          command: python -m pip show botocore
-
-      - run:
-          name: Install Ansible
-          command: |
-            python -m pip install ansible
-
-      - run:
-          name: Check and Install Specific Version of amazon.aws Collection
-          command: |
-            if ! ansible-galaxy collection list | grep -q 'amazon.aws'; then
-              echo "amazon.aws collection is not installed. Installing version 5.5.0..."
-              ansible-galaxy collection install amazon.aws:3.5.0
-            else
-              echo "amazon.aws collection is already installed."
-            fi
-
-      - run:
-          name: Set up SSH Key
-          command: |
-            mkdir -p ~/.ssh
-            echo "$PRIVATE_KEY"  > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-
-      - add_ssh_keys:
-          fingerprints:
-            - "	SHA256:jEeOv32OmEto8NyVF5+JukFhMiQl0zq1ivXSQXvWNLo"
-
-      - run:
-          name: Test SSH Connection
-          command: |
-            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$AWS_EC2_PUBLIC echo "SSH connection successful"
-
-      - aws-cli/setup:
-          aws_access_key_id: AWS_ACCESS_KEY_ID
-          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
-          region: AWS_DEFAULT_REGION
-
-      - run:
-          name: Set Environment Variables for Ansible
-          command: |
-            source "$BASH_ENV"
-            echo "AWS_EC2_PUBLIC: $AWS_EC2_PUBLIC"
-            echo "DB_USER: $DB_USER"
-            echo "DB_PASSWORD: $DB_PASSWORD"
-            echo "DB_HOST: $DB_HOST"
-            echo "S3_BUCKET: $S3_BUCKET"
+            echo "export AWS_EC2_PUBLIC=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`EC2publicIP`].OutputValue' --output text)" >> bash.env
+            echo "export DB_USER=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBUser`].OutputValue' --output text)" >> bash.env
+            echo "export DB_PASSWORD=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBPassword`].OutputValue' --output text)" >> bash.env
+            echo "export DB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`DBhost`].OutputValue' --output text)" >> bash.env
+            echo "export S3_BUCKET=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`S3bucketName`].OutputValue' --output text)" >> bash.env
+            echo "export ALB_HOST=$(aws cloudformation describe-stacks --stack-name << pipeline.parameters.NameBase >>-application --query 'Stacks[].Outputs[?OutputKey==`ALBendpoint`].OutputValue' --output text)" >> bash.env
+            cat bash.env
+            
+      - persist_to_workspace:
+          root: .
+          paths:
+            - bash.env
 
       - run:
           name: Run Ansible Playbook
@@ -120,12 +62,19 @@ jobs:
     docker:
       - image: cimg/ruby:3.2.3
     steps:
-      - checkout
       - attach_workspace:
           at: .
       - run:
-          command: 
-            cat bash.env >> $BASH_ENV
+          name: Load environment variables
+          command: |
+            if [ -f bash.env ]; then
+              set -o allexport
+              source bash.env
+              set +o allexport
+            else
+              echo "bash.env not found!"
+              exit 1
+            fi
       - run: ruby --version
       - run:
           name: bundle install
